version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - diabetes-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/diabetesdb  # MongoDB URI to connect to the database
    depends_on:
      - db
    networks:
      - diabetes-network

  db:
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - diabetes-network

volumes:
  db_data:

networks:
  diabetes-network:
    driver: bridge
